export const RESTAURANTS_SHOW_LOADER = 'RESTAURANTS_SHOW_LOADER';
export const RESTAURANTS_HIDE_LOADER = 'RESTAURANTS_HIDE_LOADER';
export const RESTAURANTS_SET_LIST = 'RESTAURANTS_SET_LIST';
export const REVIEW_ADD = 'REVIEW_ADD';

export const ORDER_CHANGE = 'ORDER_CHANGE';
